apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
        - name: heart-disease-api
          image: 2023ac05057/heart-disease-api:v3    #navyasaxena/heart-disease-api:v1  #
          imagePullPolicy: Always
          ports:
            - containerPort: 5001