global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-api'
    static_configs:
      - targets: ['heart-api:5001']  # Container name:port
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']