apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.config.name }}
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrapeInterval }}
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']